### ISSUE TITLE
[TODO] Website - current Issues overview

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#95]
Here is an overview of the outlying issues with the current page and site, at least the index.html:

- [ ] Navbar
     a) There should be a user icon, mail icon, bell icon (for notifications) and also use the MDN Push and Notification library.  This will be mainly for blog functions of the site. use the appropriate FontAwesome icons in reusableicons.html instead of png's in /Images/

https://developer.mozilla.org/en-US/docs/Web/API/Push_API

https://developer.mozilla.org/en-US/docs/Web/API/Notification

- [ ]  Login button
   
    Needs a password strength indication and some way to prevent the default passwords.  
    Consider using the TAOTPassword.js file.

    The modal's Forgot Password? link currently routes to /#, needs a forgot password function.  (Possibly jQuery?) possibly a link to a forgot password form.  

    Forgot password validation should be jQuery/Ajax and #rules : 

    A password should be alphanumeric.
    First letter of the password should be capital.
    Password must contain a special character (@, $, !, &, etc).
    Password length must be greater than 8 characters.
    One of the most important that the password fields should not be empty.
    SHA256 compliant?

- [ ]  Contact page appears to be not styled correctly
    a) Think this is still due to the fact there are two TAOT.css files in the repository.

- [ ]  Some items are not built yet, or not routed properly

   **{From Topnav}**
   These are GET errors from the server, from index.htm or /:
   a) http://127.0.0.1:5500/website/blog/blog.html {should render the blog.html} 
   b) Clicking on About routes to: http://127.0.0.1:5500/website/# {does not render the about.html}
       1) The current text from index.html should be made into the about.html
   c) Clicking on Contact should render a page contact.html  http://127.0.0.1:5500/website/contact.html.  It does but there are still styling issues.
       The correct style page is in /website/styles/TAOT.css
       There is another TAOT.css in /taotnpwaft/TAOT.css

   **{From Left Sidenav}**
   a) Clicking on Members should render users.html (possibly rename?) 
       1) users.html not built yet.  gives a GET error from the server .  Users component should 
   b) Clicking on Chat should render chat.html.  Chat is not functional, however there is stub code for chat page in website/chat/
       1) there should be enough stub code in /website/chat/ to produce a working chat, with some slight modification.
  
   d) Clicking on Settings should render settings.html {http://127.0.0.1:5500/website/settings.html} 
   e) Admin panel is rendering a card/panel may be larger than needs to be.  It's also not completed yet.

- [ ]  SEO issues from Google Lighthouse
    a) Open site using a localhost Live Server, as in VSCode Live Server.
    b) Copy link to Google Chrome.
    c)  Open the inspector and click on the tab marked Lighthouse and run the tests.

- [ ] serviceWorker needs built.. not sure what needs to be service worked.  
      More research needed.  
     see: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

The manifest loads correctly in firefox and it seems to load the manifest.json file. Not the webmanifest.
     
- [ ]  Contrast and accessibility issues.

- [ ]  Fix library vulnerability issues. 
      Decide what CDN and/or downloaded ibraries to keep.
      Toastr, Mustache, jQWidgets, jQuery-UI all list vulnerabilities.
      Bootstrap 5+ has Toasts built in. Ok to remove all references and files related to Toastr including the CDN and files in website/Scripts/
   
    See: https://getbootstrap.com/docs/5.1/components/toasts/

- [ ] Add CookieLaw stuff using cookielaw CDN provided in the index.html scripts at the bottom of the html file.

- [ ] Lighthouse says that Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes.

- [ ]  Page loading speed (index.html) needs some testing in Chrome and Firefox and other browsers.  It's not fast but not slow.

- [ ]  a resource jqx-all.js from jQWidgets is delivering some horrible results.  Especially in Firefox. 

- [ ]  The Admin menu choice in the left Nav drawer should be hidden and/or disabled by default unless, logged in and user is set as an Admin in the database, etc. 
 
- [ ]  Fix and style the Admin page, admin.html 
       a) Fix navigation for panel.  
       b) Admin & Moderation functions (Ban, etc.)
       c) Blog panel with text area for creating blog post and controls (edit, comment, thumbs up, thumbs up, heart/like, share,     save and file controls?

- [ ] Blog page content (blog.html) 
     a) Accessible from left nav drawer
     b) logged in users may get the ability to post blogs, with the right credentials
     c) Basic CMS.  Blog posting container
         1. Text Area
         2. Social Icons (share, like, heart, comment, thumbs up, thumbs down, etc)
         3. Timestamps
         4. author identification (username)
         5. file upload
         6. iframe for video
         7. Blog tags / hashtags
         8. comment area
         9. * or ranking area
         10.  Title and subtitle?
         11.  photo / video upload area
         12. Admin/Moderation of comments and or removal of blog posts, comments, etc.
         13.  sends out notifications of new items/posts
  
- [ ] Finish the TAOT .drawio file and/or create a figma.
 
- [ ] Content for index.html or / (root) should be:
       a) some Call To Action's.  (Getting a new user to subscribe, register, etc.)
       b) popular blog posts on the right sidebar 
       c) regular posting group updates
       d) easily reachable links to group meta
       e) easily reachable links to other group sites, forums, chat, blogs, etc., etc.
       f)  notifications for new blog posts (logged in users)
       g) notifications for new messages 
       h) easily contact information for group

**Comment by gbowne1** [comment]
@Trupti0406 , @NaincyKumariKnoldus , @Mahad410 , @HritikR have any of you decided what to work on of these issues?

Let me know.  I am going to be adding a draw.io template to use in design and probably work on a Figma

@idormain, @callowcreation, @mckinnon81, @RyanKHawkins, @OdatNurd, @swathe.. let me kbow if you have any ideas.  

Thank you! 😀

**Comment by Mahad410** [comment]
I will look into it and then tell you

**Comment by gbowne1** [comment]
Ok @Mahad410  Let me know.  There's a small number of issues to tackle before the next major hurdle, which should be actual content instead of what amounts to lorem ipsum.

**Comment by Mahad410** [comment]
Ummm tell me all the issues i will pick some of them to resolve

**Comment by gbowne1** [comment]
@Mahad410  Have you looked at the first post in this issue?  Thats most of the current issues.

**Comment by Mahad410** [comment]
Ok i will start working on navbar asap

**Comment by gbowne1** [comment]
Ok.  Let me know if you need any information thst may help you @Mahad410

**Comment by Mahad410** [comment]
I need the path to the html file and css files

**Comment by gbowne1** [comment]
The website files are in /website/  along with the CSS files, TAOT.css and TAOTtheme.css 

https://github.com/gbowne1/taotnpwaft/tree/master/website

the root/main page is https://github.com/gbowne1/taotnpwaft/blob/master/website/index.html

The styles are in https://github.com/gbowne1/taotnpwaft/tree/master/website/styles

**Comment by Mahad410** [comment]
Ok thank you

**Comment by HritikR** [comment]
@gbowne1 I would be working on the register button.

**Comment by gbowne1** [comment]
@HritikR ok, Yeah, I haven't really decided what to name everything so that the modal works.  The register component modal needs quite a few things more than the login.  
   1) creating and confirming/verifying new password and username
   2) entering email
   3) Accepting terms & use policy
   4) "Already have an account?" button that switches modal to login.
   5) acceptable password miniumum 8 characters.
   6) toggle password visibility with a :eye:  icon.
   7) The user should then be redirected to a profile create page, ideally profile.html.
   
    Something like this example: 
    
![Screenshot 2022-04-21 at 21-25-06 22 HTML5 Signup   Registration Forms - HTML CSS Free   Premium Templates](https://user-images.githubusercontent.com/47549872/164602370-fe891b15-95fa-446d-b1f6-1294ccc27412.png)

**Comment by gbowne1** [comment]
@HritikR Thank you! That commit push you did works great.  I just tested it.  That was the majority of the main page problems.

**Comment by gbowne1** [comment]
Updated OP.

**Comment by gbowne1** [comment]
@HritikR  the login and register modal still does not have unique enough `id=` fields between the two modals

I tested your commit/push from @Mahad410, Did you miss the search component?
There should be a tiny bit of space between the two buttons for mobile and screen reader usage as well as accessibility.  Should they be focus-able content?

I wish there was an easy way to make the header, nav and footer reusable between pages.. so that body ;; main are the only thing that changes.  

I did some mobile/tablet view testing in Firefox, other than Kindle and iPad, they don't look great at all.  

I would like to use the icons from reusableicons.html from FontAwesome for the user, notifications, etc. rather than the png's in Images/

We still do not have a favicon.  

Let's work on getting the Admin panel and the blog page ready in the next couple weeks.  I'd like to use Bootstrap's card and container for the container and its modules.  The container should be almost full width on desktop, I'd say minimum 75%.. max about to leave a margin.  I left some useable stuff on that page.

@davefol PNG Images?

**Comment by HritikR** [comment]
@gbowne1 We can remove the following `ids`
- txtUserName
- txtEmail
- txtPassword
The above specified `ids` belong to the span (font awesome icon container) of the input field. 
IDs  are not really necessary for those elements.

**Comment by gbowne1** [comment]
@HritikR  yeah, I agree with that. Icons would be great here for visibility but not completely necessary.

Yeah, if a user clicks on any page of our site it should largely look the same between the header and footer and nav component.  The only content that should change from page to page should be anything in the <body> ;; <main> and any sections, asides etc.

Still a number of outlaying issues but nothing major.  I've re-updated the OP in this thread.

**Comment by gbowne1** [comment]
What I also realized today is that there is no log out function. :-1: |

**Comment by gbowne1** [comment]
@HritikR @Mahad410 Its been ~26 days since I posted this particular group of issues.  I haven't had a lot of time to work on anything.  Have either of you decided what to work on next?

Actually I think of the 40 issues most of them sort of overlap each other, and I'd like to redo most of them.

The entirety of the repository is getting pretty big and really needs a big cleanup and organization. If not remove things but to move untested code to the 'test' branch. I would also like to move settings and project related stuff into a config/settings folder.  We can make a projects repo once we move to an organization repo.

I'd like to see the blog, chat or the admin panel working.

**Comment by HritikR** [comment]
@gbowne1 I have been working on the header, and footer part. I will send PR soon.

**Comment by gbowne1** [comment]
Ok great! Thanks! @HritikR I am going to work on moving the repository to https://github.com/taotnpwaft so that we can be a bit more organized too.  @Mahad410 @HritikR  Let me know what you think needs moved over and where.

The website can go into https://github.com/taotnpwaft/website/

I sent out the ~20 invites to the new Org mode repository.

**Comment by gbowne1** [comment]
@HritikR @Mahad410 @Trupti0406@ @NaincyKumariKnoldus and anyone else working on the website.  I will be finished moving the website files to the new repository by Tuesday evening US Time. Into https://github.com/taotnpwaft/website/ probably a good idea to start using the new repository.   

I will then migrate the most relevant issues from the issues tab here and we can have agroup discussion in the discussion tab.


If you would like added or need an invite to the project  website team let me know.

The website repo needs branches defined in the new contrib documents.

I finished creating the projects folder with configs to https://github.com/taotnpwaft/projects/.  Look in /config for the settings.  This will make it easy to get started on new group projects.  

I think the first project should be a project tracker app in NodeJS and Express.

I deleted all the configs & settings files from this repository tonight.

Sorry this repository was a bit of a mess.

As for the .NET site, am only saving a portion of that project as we early on did not really decide what .NET technology to use.
